Added upgradable contraintLimits
daostack/arc pull request #798
Opened 2020-10-13 18:52 UTC by nicoelzer

2020-10-13 20:54 UTC, orenyodfat requested changes

2020-10-13 20:54 UTC, orenyodfat commented on contracts/schemes/DxDaoSchemeConstraints.sol
> +     * @param _contractsAddresses - The contract that should be update
contracts

2020-10-13 20:54 UTC, orenyodfat commented on contracts/schemes/DxDaoSchemeConstraints.sol
> +     * @param _tokensAddresses - The token that should be updated
tokens

2020-10-13 20:54 UTC, orenyodfat commented on contracts/schemes/DxDaoSchemeConstraints.sol
> +    function updatePeriodLimitWei(uint256 _periodLimitWei) external {
why not consolidate all these 3 functions to a single one ?

2020-10-13 21:02 UTC, orenyodfat commented
so the idea is to have other genericscheme with different gov params which will  white list the schemeConstraint contract ?
other 2 alternative to do so are : 
1. add updateSchemeConstraint function to the genericSchemeMultiCall contract.
2. use the already exist plugin manager scheme to update the genericSchemeMultiCall as a whole. 

Please note that option 2 is already available and exist any how.. what is the rational/gain to add another way to do that ?

2020-10-14 03:59 UTC, nicoelzer commented
> so the idea is to have other genericscheme with different gov params which will white list the schemeConstraint contract ?
> other 2 alternative to do so are :
> 
> 1. add updateSchemeConstraint function to the genericSchemeMultiCall contract.
> 2. use the already exist plugin manager scheme to update the genericSchemeMultiCall as a whole.
> 
> Please note that option 2 is already available and exist any how.. what is the rational/gain to add another way to do that ?

Hi @orenyodfat,

exactly the idea would be to use another generic scheme with super safe governance parameters. A proposal should not be able to pass faster then 14 days. 

The reasons why a separate GenericScheme might be helpful for me are:
1. Differenciated, safer governance params then MultiCall & Plugin Manager
2. Being able to update the limits while the periodSpending are not lost. If we update the MultiCall as a whole we would also reset the spendingLimits of any token/eth.

2020-10-14 09:48 UTC, orenyodfat commented
> > so the idea is to have other genericscheme with different gov params which will white list the schemeConstraint contract ?
> > other 2 alternative to do so are :
> > 
> > 1. add updateSchemeConstraint function to the genericSchemeMultiCall contract.
> > 2. use the already exist plugin manager scheme to update the genericSchemeMultiCall as a whole.
> > 
> > Please note that option 2 is already available and exist any how.. what is the rational/gain to add another way to do that ?
> 
> Hi @orenyodfat,
> 
> exactly the idea would be to use another generic scheme with super safe governance parameters. A proposal should not be able to pass faster then 14 days.
> 
> The reasons why a separate GenericScheme might be helpful for me are:
> 
> 1. Differenciated, safer governance params then MultiCall & Plugin Manager
> 2. Being able to update the limits while the periodSpending are not lost. If we update the MultiCall as a whole we would also reset the spendingLimits of any token/eth.

this add another complexity to the system . another things to look on and monitor .

2020-10-15 07:16 UTC, orenyodfat commented on contracts/schemes/DxDaoSchemeConstraints.sol
> +                require(contractsWhiteListMap[contractToCall] == true, "tokenNotWhitelisted");
this is redundant

2020-10-15 07:18 UTC, orenyodfat commented on contracts/schemes/DxDaoSchemeConstraints.sol
>                      amount := mload(add(callData, 68))
if the whitelist is updated there is a need to re check the spender

2020-10-15 07:46 UTC, orenyodfat requested changes
please emit an event on all updates functions

2020-10-15 12:35 UTC, orenyodfat commented on contracts/schemes/DxDaoSchemeConstraints.sol
> +        address _contractAddress,
how about passing the whole array .

2020-10-15 12:35 UTC, orenyodfat commented on contracts/schemes/DxDaoSchemeConstraints.sol
> +        address _tokenAddress,
just pass the whole array

2020-10-15 13:16 UTC, nicoelzer commented on contracts/schemes/DxDaoSchemeConstraints.sol
> +        address _contractAddress,
Has been addresses in newest commit

2020-10-15 13:16 UTC, nicoelzer commented on contracts/schemes/DxDaoSchemeConstraints.sol
> +        address _tokenAddress,
Has been addresses in newest commit

2020-10-15 13:20 UTC, orenyodfat requested changes
please base this pr vs master (or open a new one)

2020-10-15 13:22 UTC, orenyodfat commented on contracts/schemes/DxDaoSchemeConstraints.sol
> +            emit UpdatedContractsWhitelist(_contractsAddresses, _contractsWhitelisted);
this should be out of the loop :)

2020-10-15 13:23 UTC, orenyodfat commented on contracts/schemes/DxDaoSchemeConstraints.sol
> +            emit UpdatedPeriodLimitsTokens(_tokensAddresses, _tokensPeriodLimits);
this should be out of the loop.
you should have a test which check that only a single event is emitted here

2020-10-15 17:06 UTC, orenyodfat commented on test/genericschememulticall.js
> -    it("schemeconstrains token value exceed limit", async function() {
Why this test was removed ?

2020-10-15 17:06 UTC, orenyodfat commented on test/genericschememulticall.js
> +       var tx = await testSetup.GenericSchemeMultiCall.proposeCalls([actionMock.address],[callData],[0],helpers.NULL_HASH);
Why change that to UpperCase .?

2020-10-15 17:08 UTC, orenyodfat commented on test/genericschememulticall.js
> +   testSetup.GenericSchemeMultiCall = await GenericSchemeMultiCall.new();
why rename that ?

2020-10-15 20:12 UTC, orenyodfat commented on test/genericschememulticall.js
> +          0,
this will revert due to 0 periodSize and not due to wrong array length.

2020-10-15 20:20 UTC, orenyodfat commented on test/genericschememulticall.js
> +           [actionMock.address],
this will revert due to wrong array length and not due to the spender not white listed

2020-10-16 12:15 UTC, merged