DAOToken is none upgradable proxy
daostack/arc pull request #799
Opened 2020-10-17 22:57 UTC by orenyodfat

2020-10-17 23:19 UTC, dkent600 requested changes

2020-10-17 23:19 UTC, dkent600 commented on contracts/utils/DAOFactory.sol
> +    function createNoneUpgradableInstance(uint64[3] memory _packageVersion,
misspelled.  should be everywhere `createNonUpgradableInstance`

2020-10-17 23:19 UTC, dkent600 commented on contracts/utils/DAOFactory.sol
> +   * @dev createNoneUpgradableInstance creates a new proxy for the given contract and forwards a function call to it.
This description of the function doesn't seem to match the function name.

2020-10-18 09:15 UTC, ben-kaufman approved these changes

2020-10-18 09:20 UTC, merged